name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
  merge_group:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  maketest:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./libsql-sqlite3

    steps:
    - uses: actions/checkout@v3

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3
    
    - name: get TCL
      run: sudo apt-get install -y tcl8.6-dev

    - name: Install Protoc
      uses: arduino/setup-protoc@v2

    - name: Install Wasmpack
      uses: jetli/wasm-pack-action@v0.4.0
      with:
        version: 'latest'

    - name: configure
      run: ./configure
      
    - name: Run tests
      run: make test

    # Rust tests are run under maketestwasm

    - name: Run API tests
      run: make testlibsql
